name: Check deployed package

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Publish Logdash dotnet client to NuGet']
    types:
      - completed
    branches:
      - main

jobs:
  run-demo:
    name: Run LogDash Demo
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Wait for package propagation
        run: sleep 60

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make run script executable
        run: chmod +x check-deployed-package/run.sh

      - name: Run LogDash demo
        env:
          LOGDASH_API_KEY: ${{ secrets.LOGDASH_API_KEY }}
        run: ./check-deployed-package/run.sh
